/** Fictional fixtures for previewing the panel without an API (`VITE_ADMIN_DEMO=true npm run dev:admin`). Never enabled in production builds unless that variable is set. */
const day=86_400_000;const now=Date.now();const iso=(offset:number)=>new Date(now-offset).toISOString();
const sources=[['google-ai-overview','simulated','Google AI Overview · User-simulated response','serpapi','SerpApi',3_200,18,5_400],['google-ai-mode','simulated','Google AI Mode · User-simulated response','serpapi','SerpApi',3_200,22,6_100],['bing-copilot','simulated','Bing Copilot · User-simulated response','serpapi','SerpApi',2_900,41,7_900],['duckduckgo-search-assist','simulated','DuckDuckGo · User-simulated response','serpapi','SerpApi',2_600,9,4_200],['naver-ai-overview','simulated','Naver · User-simulated response','serpapi','SerpApi',800,3,4_800],['chatgpt','api','ChatGPT · Direct API','openai','OpenAI',3_000,12,9_800],['chatgpt','simulated','ChatGPT · User-simulated response','oxylabs','Oxylabs',1_400,96,74_000],['perplexity','api','Perplexity · Direct API','perplexity','Perplexity',2_700,15,6_900],['perplexity','simulated','Perplexity · User-simulated response','oxylabs','Oxylabs',900,61,81_000]] as const;
const unit:Record<string,number>={serpapi:15_000,openai:11_500,perplexity:8_200,oxylabs:4_000};
const lines=sources.map(([provider,method,label,vendor,,calls,failures,p50])=>({key:`${provider}:${method}`,label,calls,successes:calls-failures,failures,costMicros:(calls-failures)*unit[vendor],costPerCheckMicros:Math.round((calls-failures)*unit[vendor]/calls),costPerSuccessMicros:unit[vendor],unpricedCalls:0,share:0,errorRate:failures/calls,p50Ms:p50,p95Ms:p50*2.6,errors:failures?[{code:failures>40?'PROVIDER_TIMEOUT':'PROVIDER_RATE_LIMIT',count:failures}]:[]}));
const total=lines.reduce((n,l)=>n+l.costMicros,0);lines.forEach(l=>{l.share=l.costMicros/total});lines.sort((a,b)=>b.costMicros-a.costMicros);
const accounts=[['acc_northwind','Northwind Labs','active',6999,4_100,'2026-03-02'],['acc_bluefin','Bluefin Outdoor','active',6999,3_600,'2026-04-18'],['acc_harbor','Harbor & Pine Legal','past_due',6999,2_200,'2026-05-09'],['acc_quill','Quill Analytics','active',6999,5_300,'2026-06-21'],['acc_sola','Sola Dental Group','active',6999,1_900,'2026-08-30'],['acc_trial','Meridian Freight (comp)','trialing',0,2_600,'2026-09-15']] as const;
const perCheck=total/lines.reduce((n,l)=>n+l.calls,0);
const accountRows=accounts.map(([id,name,sub,price,checks,created],i)=>{const cost=Math.round(checks*perCheck);const revenue=price+(i===3?950:0);return{id,name,createdAt:`${created}T10:00:00Z`,subscriptionStatus:sub,planId:'starter',monthlyPrice:price,status:i===2?'paused':'active',addonWaived:i===1,maxQueriesOverride:null,lastRunAt:iso(i*day/3+3_600_000),checks,failures:Math.round(checks*0.012),costMicros:cost,revenueCents:revenue,marginRate:revenue?(revenue*10_000-cost)/(revenue*10_000):null}});
const margins=accountRows.map(a=>({accountId:a.id,accountName:a.name,revenueCents:a.revenueCents,costMicros:a.costMicros,marginMicros:a.revenueCents*10_000-a.costMicros,marginRate:a.marginRate})).sort((a,b)=>a.marginMicros-b.marginMicros);
const mrr=accountRows.filter(a=>a.subscriptionStatus!=='trialing').reduce((n,a)=>n+a.monthlyPrice,0);
const business={mrrCents:mrr,arrCents:mrr*12,mrrAtRiskCents:6999,payingAccounts:5,pastDue:1,newSubscriptions:2,churned:1,churnRate:1/5,arpaCents:Math.round(mrr/5),addonRevenueCents:950,byPlan:[{planId:'starter',accounts:5,mrrCents:mrr}],byStatus:{active:4,past_due:1,trialing:1,canceled:2}};
const revenueCents=accountRows.reduce((n,a)=>n+a.revenueCents,0);
let routing:{simulatedVendors:Record<string,string>;disabledSources:string[]}={simulatedVendors:{},disabledSources:['naver-ai-overview:simulated']};
const rates:Record<string,number|null>={};
const months=Array.from({length:12},(_,i)=>{const d=new Date(now);d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()-11+i);return d.toISOString().slice(0,7)});
const deployments=[['READY','production','main','5fbb192','Merge pull request #9',58_000],['READY',null,'claude/admin-dashboard','a1c9e02','Add operator control panel',61_000],['ERROR',null,'codex/brand-color',null,'Change brand color',0],['READY','production','main','6980304','Add project status notes',55_000],['READY',null,'claude/perplexity','4800268','Collection methods by location',63_000]] as const;
const audit=[['admin.routing.updated',null,{after:{disabledSources:['naver-ai-overview:simulated']}}],['admin.account.controls_updated','acc_harbor',{after:{paused:true}}],['admin.rates.updated',null,{rates:[{vendor:'oxylabs',provider:'chatgpt',method:'simulated',unitCostMicros:4000}]}],['admin.login',null,{}]] as const;

export function demoResponse(path:string,init:{method?:string;body?:unknown}):unknown{const url=new URL(path,'https://demo.local');const p=url.pathname;
  if(p==='/auth/session'||p==='/auth/verify')return{success:true,operator:{email:'ops@aioverviewhub.com',name:'Demo operator'}};
  if(p.startsWith('/auth/'))return{success:true};
  if(p==='/overview')return{success:true,business,revenueCents,costMicros:total,checks:lines.reduce((n,l)=>n+l.calls,0),grossMarginRate:(revenueCents*10_000-total)/(revenueCents*10_000),topSources:lines.slice(0,5),health:{runs:{COMPLETED:182,COMPLETED_WITH_ERRORS:11,FAILED:1},jobs:{SUCCESS:2400,FAILED:2},failedJobs:2,webhooks:{PROCESSED:38},degradedSources:lines.filter(l=>l.errorRate>0.05).map(l=>({key:l.key,label:l.label,errorRate:l.errorRate}))}};
  if(p==='/costs'){const by=url.searchParams.get('by')??'source';const daily=Array.from({length:30},(_,i)=>{const d=new Date(now-(29-i)*day).toISOString().slice(0,10);const weekday=new Date(d).getUTCDay();const factor=[0.35,1.2,1,1.05,0.95,0.9,0.4][weekday];return{day:d,costMicros:Math.round(total/30*factor),calls:Math.round(lines.reduce((n,l)=>n+l.calls,0)/30*factor)}});
    const grouped=by==='vendor'?Object.values(lines.reduce<Record<string,typeof lines[number]>>((acc,l)=>{const v=sources.find(s=>`${s[0]}:${s[1]}`===l.key)!;const cur=acc[v[3]]??{...l,key:v[3],label:v[4],calls:0,successes:0,failures:0,costMicros:0,share:0};cur.calls+=l.calls;cur.successes+=l.successes;cur.failures+=l.failures;cur.costMicros+=l.costMicros;cur.share+=l.share;cur.costPerCheckMicros=Math.round(cur.costMicros/cur.calls);cur.costPerSuccessMicros=Math.round(cur.costMicros/cur.successes);acc[v[3]]=cur;return acc},{})).sort((a,b)=>b.costMicros-a.costMicros):by==='account'?accountRows.map(a=>({key:a.id,label:a.name,calls:a.checks,successes:a.checks-a.failures,failures:a.failures,costMicros:a.costMicros,costPerCheckMicros:Math.round(a.costMicros/a.checks),costPerSuccessMicros:Math.round(a.costMicros/(a.checks-a.failures)),unpricedCalls:0,share:a.costMicros/total})).sort((a,b)=>b.costMicros-a.costMicros):lines;
    return{success:true,by,lines:grouped,daily,totalMicros:total,unpricedCalls:by==='source'?0:0,margins:by==='account'?margins:undefined}}
  if(p==='/business')return{success:true,...business,revenueCents,costMicros:total,trend:months.map((month,i)=>({month,new:[0,1,0,1,1,1,0,1,2,1,1,1][i],churned:[0,0,0,0,0,1,0,0,0,1,0,1][i]})),margins};
  if(p==='/operations')return{success:true,sources:lines,jobs:{SUCCESS:2400,RETRY:3,FAILED:2},failedJobs:[{id:'job_8f2',accountId:'acc_quill',projectId:'prj_q1',jobType:'RUN_QUERY',attempts:3,errorCode:'PROVIDER_TIMEOUT',requestId:'req_4d1e0b',updatedAt:iso(5_400_000)},{id:'job_8e9',accountId:'acc_bluefin',projectId:'prj_b2',jobType:'EXPORT',attempts:3,errorCode:'EXPORT_ERROR',requestId:'req_77a2c9',updatedAt:iso(day)}],runs:{COMPLETED:182,COMPLETED_WITH_ERRORS:11,FAILED:1},webhooks:{PROCESSED:38}};
  if(p==='/vercel')return{success:true,projects:[{projectId:'prj_web',name:'ai-overview-hub',total:5,failed:1,successRate:0.8,buildP50Ms:59_500,buildP95Ms:63_000,dashboardUrl:'https://vercel.com/dashboard',lastProduction:{id:'d0',url:'',state:'READY',target:'production',createdAt:now-2*3_600_000,buildMs:58_000,commit:'5fbb192',message:'Merge pull request #9'},deployments:deployments.map(([state,target,branch,commit,message,build],i)=>({id:`d${i}`,url:'',state,target,branch,commit:commit??undefined,message,createdAt:now-(i*7+2)*3_600_000,buildMs:build||null}))}]};
  if(p==='/sources'){if(init.method==='PUT'){routing=init.body as typeof routing;return{success:true,routing}}const envVendor:Record<string,string>={chatgpt:'oxylabs',perplexity:'oxylabs'};return{success:true,routing,sources:sources.map(([provider,method,label,vendor,vendorName])=>{const key=`${provider}:${method}`;const switchable=method==='simulated'&&(provider==='chatgpt'||provider==='perplexity');const effective=switchable?routing.simulatedVendors[provider]??envVendor[provider]:vendor;const off=routing.disabledSources.includes(key);return{key,provider,method,label,vendor:effective,vendorName:effective==='dataforseo'?'DataForSEO':vendorName,envVendor:switchable?envVendor[provider]:vendor,vendorOptions:switchable?(provider==='chatgpt'?[{vendor:'oxylabs',name:'Oxylabs',configured:true},{vendor:'dataforseo',name:'DataForSEO',configured:true}]:[{vendor:'oxylabs',name:'Oxylabs',configured:true}]):[],credentialsConfigured:true,disabled:off,live:!off}})}}
  if(p==='/sources/routing'){routing=init.body as typeof routing;return{success:true,routing}}
  if(p==='/rates'){if(init.method==='PUT'){for(const r of (init.body as {rates:{vendor:string;provider:string;method:string;unitCostMicros:number|null}[]}).rates)rates[`${r.vendor}|${r.provider}|${r.method}`]=r.unitCostMicros;return{success:true}}const slots=sources.flatMap(([provider,method,label,vendor,vendorName]):{provider:string;method:string;label:string;vendor:string;vendorName:string}[]=>method==='simulated'&&provider==='chatgpt'?[['oxylabs','Oxylabs'],['dataforseo','DataForSEO']].map(([v,n])=>({provider,method,label,vendor:v,vendorName:n})):[{provider,method,label,vendor,vendorName}]);return{success:true,rates:slots.map(s=>{const k=`${s.vendor}|${s.provider}|${s.method}`;const reportsCost=s.vendor==='perplexity'||s.vendor==='dataforseo';return{...s,reportsCost,unitCostMicros:k in rates?rates[k]:reportsCost?null:unit[s.vendor],updatedAt:iso(3*day)}})}}
  if(p==='/accounts')return{success:true,accounts:accountRows.filter(a=>a.name.toLowerCase().includes((url.searchParams.get('q')??'').toLowerCase()))};
  const account=/^\/accounts\/([^/]+)(\/controls)?$/.exec(p);if(account){const a=accountRows.find(r=>r.id===decodeURIComponent(account[1]))??accountRows[0];if(account[2])return{success:true};return{success:true,account:{id:a.id,name:a.name,createdAt:a.createdAt},controls:{paused:a.status==='paused',routing:{simulatedVendors:{},disabledSources:[]},maxQueriesOverride:null,addonWaived:a.addonWaived},subscriptions:[{id:'sub_1',planName:'AI Visibility Starter',status:a.subscriptionStatus,monthlyPrice:a.monthlyPrice,periodEnd:iso(-12*day),createdAt:a.createdAt,canceledAt:null}],projects:[{id:'prj_1',name:`${a.name} — US`,primaryDomain:`${a.id.slice(4)}.example`,frequency:'monthly',lastRunAt:a.lastRunAt}],runs:Array.from({length:4},(_,i)=>({id:`run_${i}`,status:i===1?'COMPLETED_WITH_ERRORS':'COMPLETED',createdAt:iso(i*7*day+day),checks:Math.round(a.checks/4),failures:i===1?6:0,costMicros:Math.round(a.costMicros/4)})),members:[{email:`owner@${a.id.slice(4)}.example`,role:'owner'}],costs:lines.map(l=>({...l,calls:Math.round(l.calls*a.checks/21_700),costMicros:Math.round(l.costMicros*a.checks/21_700)}))}}
  if(p.startsWith('/jobs/'))return{success:true,status:'PENDING'};
  if(p==='/audit')return{success:true,events:audit.map(([type,accountId,metadata],i)=>({id:`ev${i}`,accountId,type,requestId:`req_${i}`,metadata:{operator:'ops@aioverviewhub.com',...metadata},createdAt:iso(i*day/2+600_000)}))};
  throw new Error(`No demo data for ${p}`)}
