import {readFileSync,readdirSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {beforeEach,describe,expect,it,vi} from 'vitest';
import {base32Decode,base32Encode,decryptSecret,encryptSecret,totp,verifyTotp} from '../packages/admin/src/auth';
import {accountMargins,businessMetrics,callCost,costBreakdown,parseRange,percentile} from '../packages/admin/src/metrics';
import type {CallGroup} from '../packages/admin/src/metrics';
import {applyRouting,maskAvailability,parseRouting,readRouting,sourceVendor} from '../packages/admin/src/routing';
import {projectHealth} from '../packages/admin/src/vercel';
import {providerConfigFromEnv,sourceAvailability} from '../packages/providers/src/index';

/** D1-compatible adapter over node:sqlite with every migration applied, so admin SQL is exercised against the real schema. */
function d1(){const db=new DatabaseSync(':memory:');for(const file of readdirSync('migrations').sort())db.exec(readFileSync(`migrations/${file}`,'utf8'));const norm=(v:unknown[])=>v.map(x=>x===undefined?null:typeof x==='boolean'?Number(x):x) as (string|number|null)[];const statement=(sql:string,values:unknown[]=[])=>({first:async<T>()=>(db.prepare(sql).get(...norm(values))??null) as T|null,all:async<T>()=>({results:db.prepare(sql).all(...norm(values)) as T[]}),run:async()=>({meta:{changes:Number(db.prepare(sql).run(...norm(values)).changes)}})});return{raw:db,binding:{prepare:(sql:string)=>({...statement(sql),bind:(...values:unknown[])=>statement(sql,values)})}}}

describe('admin routing',()=>{const env=providerConfigFromEnv({OXYLABS_USERNAME:'u',OXYLABS_PASSWORD:'p',DATAFORSEO_LOGIN:'l',DATAFORSEO_PASSWORD:'p',SERPAPI_API_KEY:'s'});
  it('validates overrides',()=>{expect(()=>parseRouting({simulatedVendors:{perplexity:'dataforseo'}})).toThrow(/cannot be simulated/);expect(()=>parseRouting({disabledSources:['naver-ai-overview:api']})).toThrow(/Unknown source/);expect(parseRouting({simulatedVendors:{chatgpt:'dataforseo',perplexity:''},disabledSources:['bing-copilot:simulated','bing-copilot:simulated']})).toEqual({simulatedVendors:{chatgpt:'dataforseo'},disabledSources:['bing-copilot:simulated']})});
  it('falls back to no overrides for corrupt stored JSON',()=>{expect(readRouting('{oops')).toEqual({simulatedVendors:{},disabledSources:[]});expect(readRouting(JSON.stringify({simulatedVendors:{perplexity:'dataforseo'}}))).toEqual({simulatedVendors:{},disabledSources:[]})});
  it('layers global then account overrides and masks disabled sources',()=>{const {config,disabled}=applyRouting(env,{simulatedVendors:{chatgpt:'dataforseo'},disabledSources:['bing-copilot:simulated']},{simulatedVendors:{chatgpt:'oxylabs'},disabledSources:['duckduckgo-search-assist:simulated']});expect(config.simulatedVendors.chatgpt).toBe('oxylabs');expect(env.simulatedVendors.chatgpt).toBe('oxylabs');const live=maskAvailability(sourceAvailability(config),disabled);expect(live['bing-copilot:simulated']).toBe(false);expect(live['duckduckgo-search-assist:simulated']).toBe(false);expect(live['google-ai-mode:simulated']).toBe(true)});
  it('names the vendor behind each source',()=>{expect(sourceVendor('google-ai-mode','simulated',env)).toBe('serpapi');expect(sourceVendor('chatgpt','api',env)).toBe('openai');expect(sourceVendor('chatgpt','simulated',{...env,simulatedVendors:{chatgpt:'dataforseo',perplexity:'oxylabs'}})).toBe('dataforseo');expect(sourceVendor('chatgpt','simulated',{...env,mock:true})).toBe('mock')})});

describe('admin metrics',()=>{const g=(o:Partial<CallGroup>):CallGroup=>({accountId:'a1',accountName:'Acme',provider:'chatgpt',method:'api',vendor:'openai',status:'SUCCESS',calls:1,costMicros:0,unpricedCalls:0,...o});
  it('prefers vendor-reported cost over operator rates',()=>{const rates=[{vendor:'openai',provider:'chatgpt' as const,method:'api' as const,unitCostMicros:12_000}];expect(callCost({cost:0.0123},'perplexity','perplexity','api',rates)).toEqual({costMicros:12_300,basis:'reported'});expect(callCost({cost:'0.5'},'dataforseo','chatgpt','simulated',rates)).toEqual({costMicros:500_000,basis:'reported'});expect(callCost({},'openai','chatgpt','api',rates)).toEqual({costMicros:12_000,basis:'rate'});expect(callCost({cost:-1},'serpapi','google-ai-mode','simulated',rates)).toEqual({costMicros:null,basis:'unknown'})});
  it('rolls cost up per source, vendor and account',()=>{const groups=[g({calls:90,costMicros:900_000}),g({status:'FAILED',calls:10}),g({accountId:'a2',accountName:'Beta',provider:'google-ai-mode',method:'simulated',vendor:'serpapi',calls:50,costMicros:250_000,unpricedCalls:5})];const bySource=costBreakdown(groups,'source');expect(bySource[0]).toMatchObject({key:'chatgpt:api',label:'ChatGPT · Direct API',calls:100,successes:90,failures:10,costMicros:900_000,costPerCheckMicros:9_000,costPerSuccessMicros:10_000});expect(bySource[0].share).toBeCloseTo(900/1150);expect(costBreakdown(groups,'vendor').map(l=>l.label)).toEqual(['OpenAI','SerpApi']);expect(costBreakdown(groups,'account')[1]).toMatchObject({key:'a2',label:'Beta',unpricedCalls:5})});
  it('computes MRR, churn and ARPA from subscriptions',()=>{const period={from:'2026-09-01T00:00:00.000Z',to:'2026-10-01T00:00:00.000Z'};const m=businessMetrics([{accountId:'a1',planId:'starter',status:'active',monthlyPrice:6999,createdAt:'2026-01-05',canceledAt:null},{accountId:'a2',planId:'starter',status:'past_due',monthlyPrice:6999,createdAt:'2026-09-10',canceledAt:null},{accountId:'a3',planId:'starter',status:'canceled',monthlyPrice:6999,createdAt:'2026-02-01',canceledAt:'2026-09-20'}],period,500);expect(m).toMatchObject({mrrCents:13998,arrCents:167976,mrrAtRiskCents:6999,payingAccounts:2,pastDue:1,newSubscriptions:1,churned:1,churnRate:0.5,arpaCents:6999,addonRevenueCents:500});expect(m.byStatus).toEqual({active:1,past_due:1,canceled:1})});
  it('computes margin per account, worst first',()=>{const costs=costBreakdown([g({costMicros:30_000_000}),g({accountId:'a2',accountName:'Comp',costMicros:1_000_000})],'account');expect(accountMargins([{accountId:'a1',accountName:'Acme',revenueCents:6999}],costs)).toEqual([{accountId:'a2',accountName:'Comp',revenueCents:0,costMicros:1_000_000,marginMicros:-1_000_000,marginRate:null},{accountId:'a1',accountName:'Acme',revenueCents:6999,costMicros:30_000_000,marginMicros:39_990_000,marginRate:39_990_000/69_990_000}])});
  it('parses ranges and percentiles',()=>{const now=new Date('2026-10-04T00:00:00Z');expect(parseRange('7d',now).from).toBe('2026-09-27T00:00:00.000Z');expect(parseRange('12m',now).from).toBe('2025-10-04T00:00:00.000Z');expect(parseRange('drop table',now).range).toBe('30d');expect(percentile([5,1,4,2,3],50)).toBe(3);expect(percentile([1,2,3,4,5,6,7,8,9,10],95)).toBe(10);expect(percentile([],50)).toBeNull()})});

describe('operator authentication primitives',()=>{const rfcSecret=new TextEncoder().encode('12345678901234567890');
  it('matches the RFC 6238 SHA-1 vectors',async()=>{expect(await totp(rfcSecret,1)).toBe('287082');expect(await totp(rfcSecret,37037036)).toBe('081804');expect(base32Decode(base32Encode(rfcSecret))).toEqual(rfcSecret)});
  it('accepts adjacent steps but never replays a used one',async()=>{const t=59_000*1000;const code=await totp(rfcSecret,Math.floor(t/30_000));expect(await verifyTotp(rfcSecret,code,0,t)).toBe(Math.floor(t/30_000));expect(await verifyTotp(rfcSecret,code,Math.floor(t/30_000),t)).toBeNull();expect(await verifyTotp(rfcSecret,'12345',0,t)).toBeNull()});
  it('encrypts authenticator secrets at rest',async()=>{const key=btoa(String.fromCharCode(...new Uint8Array(32).fill(7)));const sealed=await encryptSecret('JBSWY3DPEHPK3PXP',key);expect(sealed).not.toContain('JBSWY3DPEHPK3PXP');expect(await decryptSecret(sealed,key)).toBe('JBSWY3DPEHPK3PXP');await expect(decryptSecret(sealed,btoa(String.fromCharCode(...new Uint8Array(32))))).rejects.toThrow();await expect(encryptSecret('x',undefined)).rejects.toThrow(/not configured/)})});

describe('vercel health',()=>{it('summarizes deployments from the REST API',async()=>{const fetcher=vi.fn<typeof fetch>(async input=>new Response(JSON.stringify(String(input).includes('/v9/projects/')?{name:'ai-overview-hub'}:{deployments:[{uid:'d1',url:'a.vercel.app',readyState:'READY',target:'production',createdAt:3,buildingAt:1000,ready:61000,meta:{githubCommitRef:'main',githubCommitSha:'abcdef123',githubCommitMessage:'Ship it\nbody'}},{uid:'d2',url:'b.vercel.app',readyState:'ERROR',target:null,createdAt:2},{uid:'d3',url:'c.vercel.app',readyState:'CANCELED',createdAt:1}]})));const [p]=await projectHealth({token:'t',teamId:'team_1',teamSlug:'acme',projectIds:['prj_1']},0,fetcher);expect(String(fetcher.mock.calls[1][0])).toContain('teamId=team_1');expect(fetcher.mock.calls[0][1]?.headers).toEqual({authorization:'Bearer t'});expect(p).toMatchObject({name:'ai-overview-hub',total:3,failed:1,successRate:0.5,buildP50Ms:60000,dashboardUrl:'https://vercel.com/acme/ai-overview-hub/observability'});expect(p.lastProduction).toMatchObject({id:'d1',commit:'abcdef1',message:'Ship it'})});
  it('reports a missing connection as configuration',async()=>{await expect(projectHealth({projectIds:[]},0)).rejects.toThrow(/not connected/)})});

describe('admin API',()=>{const key=btoa(String.fromCharCode(...new Uint8Array(32).fill(3)));const secret='JBSWY3DPEHPK3PXP';let db:ReturnType<typeof d1>;let sent:unknown[];
  const env=()=>({DB:db.binding,QUEUE:{send:async(m:unknown)=>{sent.push(m)}},REPORTS:null,ADMIN_URL:'https://admin.example.com',ADMIN_ORIGIN:'https://admin.example.com',ADMIN_TOTP_KEY:key,EMAIL_PROVIDER:'console',SERPAPI_API_KEY:'s',OXYLABS_USERNAME:'u',OXYLABS_PASSWORD:'p'});
  const call=async(path:string,init:RequestInit={},cookie?:string)=>{const {default:app}=await import('../apps/api/src/index');return app.request(path,{...init,headers:{'content-type':'application/json',origin:'https://admin.example.com',...(cookie?{cookie}:{}),...init.headers}},env())};
  const startLogin=async()=>{const log=vi.spyOn(console,'log').mockImplementation(()=>{});const res=await call('/api/admin/auth/start',{method:'POST',body:JSON.stringify({email:' Ops@Example.com '})});const line=log.mock.calls.map(c=>String(c[0])).find(l=>l.includes('admin_login_link'));log.mockRestore();expect(res.status).toBe(202);return line?/#token=([\w-]+)/.exec(line)![1]:undefined};
  const signIn=async()=>{const token=await startLogin();const res=await call('/api/admin/auth/verify',{method:'POST',body:JSON.stringify({token,code:await totp(base32Decode(secret),Math.floor(Date.now()/30_000))})});expect(res.status).toBe(200);return res.headers.get('set-cookie')!.split(';')[0]};
  beforeEach(async()=>{db=d1();sent=[];db.raw.prepare('INSERT INTO operators (id,email,name,totp_secret) VALUES (?,?,?,?)').run('op1','ops@example.com','Ops',await encryptSecret(secret,key))});

  it('requires an operator session',async()=>{const res=await call('/api/admin/overview');expect(res.status).toBe(401);expect(((await res.json()) as {error:{code:string}}).error.code).toBe('AUTHENTICATION_ERROR')});
  it('signs in with an emailed link and authenticator code, once',async()=>{const token=await startLogin();expect(token).toBeTruthy();const code=await totp(base32Decode(secret),Math.floor(Date.now()/30_000));const ok=await call('/api/admin/auth/verify',{method:'POST',body:JSON.stringify({token,code})});expect(ok.status).toBe(200);const cookie=ok.headers.get('set-cookie')!;expect(cookie).toMatch(/^__Host-admin_session=[\w-]+; Path=\/; HttpOnly; Secure; SameSite=Strict/);expect((await call('/api/admin/auth/verify',{method:'POST',body:JSON.stringify({token,code})})).status).toBe(401);expect((await call('/api/admin/auth/session',{},cookie.split(';')[0])).status).toBe(200);expect(db.raw.prepare("SELECT type FROM audit_events").all()).toEqual([{type:'admin.login'}]);expect(JSON.stringify(db.raw.prepare('SELECT * FROM operator_sessions').all())).not.toContain(cookie.split(';')[0].split('=')[1])});
  it('does not reveal whether an email is an operator',async()=>{const log=vi.spyOn(console,'log').mockImplementation(()=>{});const res=await call('/api/admin/auth/start',{method:'POST',body:JSON.stringify({email:'stranger@example.com'})});expect(res.status).toBe(202);expect(log).not.toHaveBeenCalled();log.mockRestore()});
  it('locks a sign-in link after repeated wrong codes',async()=>{const token=await startLogin();for(let i=0;i<5;i++)expect((await call('/api/admin/auth/verify',{method:'POST',body:JSON.stringify({token,code:'000000'})})).status).toBe(401);const code=await totp(base32Decode(secret),Math.floor(Date.now()/30_000));expect((await call('/api/admin/auth/verify',{method:'POST',body:JSON.stringify({token,code})})).status).toBe(401)});
  it('rejects cross-origin and non-JSON mutations',async()=>{const cookie=await signIn();expect((await call('/api/admin/sources/routing',{method:'PUT',body:'{}',headers:{origin:'https://evil.example'}},cookie)).status).toBe(403);expect((await call('/api/admin/sources/routing',{method:'PUT',body:'{}',headers:{'content-type':'text/plain'}},cookie)).status).toBe(400)});
  it('switches vendors and disables sources for customers, with an audit trail',async()=>{const cookie=await signIn();expect((await call('/api/admin/sources/routing',{method:'PUT',body:JSON.stringify({simulatedVendors:{chatgpt:'dataforseo'}})},cookie)).status).toBe(400);const res=await call('/api/admin/sources/routing',{method:'PUT',body:JSON.stringify({disabledSources:['naver-ai-overview:simulated']})},cookie);expect(res.status).toBe(200);const admin=await (await call('/api/admin/sources',{},cookie)).json() as {sources:{key:string;vendorName:string;live:boolean;disabled:boolean}[]};expect(admin.sources.find(s=>s.key==='naver-ai-overview:simulated')).toMatchObject({vendorName:'SerpApi',disabled:true,live:false});const portal=await (await call('/api/sources')).json() as {providers:{id:string;methods:{available:boolean}[]}[]};expect(portal.providers.find(p=>p.id==='naver-ai-overview')?.methods[0].available).toBe(false);expect(portal.providers.find(p=>p.id==='google-ai-mode')?.methods[0].available).toBe(true);const events=db.raw.prepare("SELECT type,metadata FROM audit_events WHERE type='admin.routing.updated'").all() as {metadata:string}[];expect(JSON.parse(events[0].metadata)).toMatchObject({operator:'ops@example.com',after:{disabledSources:['naver-ai-overview:simulated']}})});
  it('reports cost per resource, revenue and margin from stored runs',async()=>{const cookie=await signIn();const at=new Date(Date.now()-86_400_000).toISOString();const r=db.raw;r.exec(`INSERT INTO accounts (id,name) VALUES ('a1','Acme'),('a2','Comped');INSERT INTO users (id,email) VALUES ('u1','owner@acme.test');INSERT INTO account_users VALUES ('a1','u1','owner');UPDATE plans SET addon_unit_price=5 WHERE id='starter';INSERT INTO subscriptions (id,account_id,plan_id,stripe_customer_id,status,updated_at,created_at) VALUES ('s1','a1','starter','cus_1','active','${at}','${at}');INSERT INTO projects (id,account_id,name,primary_domain,providers,created_at) VALUES ('p1','a1','Acme','acme.test','[]','${at}'),('p2','a2','Comp','comp.test','[]','${at}');INSERT INTO queries (id,account_id,text,created_at) VALUES ('q1','a1','best crm','${at}'),('q2','a2','best crm','${at}');INSERT INTO runs (id,account_id,project_id,status,idempotency_key,request_id,created_at) VALUES ('r1','a1','p1','COMPLETED','k1','req','${at}'),('r2','a2','p2','COMPLETED','k2','req','${at}');INSERT INTO run_queries (id,run_id,query_id,provider_id,method,status,vendor,cost_micros,cost_basis,duration_ms,completed_at) VALUES ('rq1','r1','q1','chatgpt','api','SUCCESS','openai',20000,'rate',4000,'${at}'),('rq2','r1','q1','chatgpt','simulated','SUCCESS','oxylabs',30000,'rate',90000,'${at}'),('rq3','r1','q1','google-ai-mode','simulated','FAILED','serpapi',NULL,NULL,1000,'${at}'),('rq4','r2','q2','chatgpt','api','SUCCESS','openai',NULL,'unknown',6000,'${at}');INSERT INTO usage_events (id,account_id,subscription_id,run_id,query_id,provider,method,addon,units,period_start,period_end,created_at) VALUES ('ue1','a1','s1','r1','q1','chatgpt','simulated',1,1,'${at}','${at}','${at}');INSERT INTO scheduled_jobs (id,account_id,project_id,job_type,status,attempts,error_code,request_id,created_at,updated_at) VALUES ('j1','a1','p1','RUN_QUERY','FAILED',3,'PROVIDER_TIMEOUT','req','${at}','${at}');`);
    const costs=await (await call('/api/admin/costs?range=7d',{},cookie)).json() as {lines:{key:string;calls:number;costMicros:number;costPerCheckMicros:number}[];totalMicros:number;unpricedCalls:number};expect(costs.totalMicros).toBe(50_000);expect(costs.unpricedCalls).toBe(1);expect(costs.lines.find(l=>l.key==='chatgpt:simulated')).toMatchObject({calls:1,costMicros:30_000});expect(costs.lines.find(l=>l.key==='chatgpt:api')).toMatchObject({calls:2,costMicros:20_000,costPerCheckMicros:10_000});
    const byAccount=await (await call('/api/admin/costs?range=7d&by=account',{},cookie)).json() as {margins:{accountId:string;revenueCents:number;costMicros:number}[]};expect(byAccount.margins[0]).toMatchObject({accountId:'a2',revenueCents:0});expect(byAccount.margins.find(m=>m.accountId==='a1')!.revenueCents).toBe(Math.round(6999*7/30.44)+5);
    const biz=await (await call('/api/admin/business?range=30d',{},cookie)).json() as {mrrCents:number;payingAccounts:number;addonRevenueCents:number;newSubscriptions:number};expect(biz).toMatchObject({mrrCents:6999,payingAccounts:1,addonRevenueCents:5,newSubscriptions:1});
    const ops=await (await call('/api/admin/operations',{},cookie)).json() as {sources:{key:string;errorRate:number;p95Ms:number;errors:{code:string}[]}[];jobs:Record<string,number>;failedJobs:unknown[]};expect(ops.sources.find(s=>s.key==='google-ai-mode:simulated')).toMatchObject({errorRate:1});expect(ops.sources.find(s=>s.key==='chatgpt:api')?.p95Ms).toBe(6000);expect(ops.jobs).toEqual({FAILED:1});
    const overview=await (await call('/api/admin/overview',{},cookie)).json() as {checks:number;costMicros:number;business:{mrrCents:number}};expect(overview).toMatchObject({checks:4,costMicros:50_000,business:{mrrCents:6999}});
    const retry=await call('/api/admin/jobs/j1/retry',{method:'POST',body:'{}'},cookie);expect(retry.status).toBe(202);expect(sent).toMatchObject([{type:'JOB_RETRY',jobId:'j1',accountId:'a1'}]);expect((await call('/api/admin/jobs/j1/retry',{method:'POST',body:'{}'},cookie)).status).toBe(409);
    const accounts=await (await call('/api/admin/accounts',{},cookie)).json() as {accounts:{id:string;checks:number;subscriptionStatus:string|null}[]};expect(accounts.accounts.find(a=>a.id==='a1')).toMatchObject({checks:3,subscriptionStatus:'active'});const detail=await (await call('/api/admin/accounts/a1',{},cookie)).json() as {members:unknown[];runs:{checks:number;failures:number}[]};expect(detail.members).toEqual([{email:'owner@acme.test',role:'owner'}]);expect(detail.runs[0]).toMatchObject({checks:3,failures:1})});
  it('updates per-account controls and vendor rates with validation',async()=>{const cookie=await signIn();db.raw.exec("INSERT INTO accounts (id,name) VALUES ('a1','Acme')");expect((await call('/api/admin/accounts/a1/controls',{method:'PUT',body:JSON.stringify({status:'deleted'})},cookie)).status).toBe(400);const res=await call('/api/admin/accounts/a1/controls',{method:'PUT',body:JSON.stringify({status:'paused',simulatedVendors:{chatgpt:'dataforseo'},disabledSources:['perplexity:simulated'],maxQueriesOverride:250,addonWaived:true})},cookie);expect(res.status).toBe(200);const {loadAccountControls}=await import('../apps/api/src/admin');expect(await loadAccountControls(db.binding,'a1')).toEqual({paused:true,routing:{simulatedVendors:{chatgpt:'dataforseo'},disabledSources:['perplexity:simulated']},maxQueriesOverride:250,addonWaived:true});expect((await call('/api/admin/accounts/missing/controls',{method:'PUT',body:'{}'},cookie)).status).toBe(404);
    expect((await call('/api/admin/rates',{method:'PUT',body:JSON.stringify({rates:[{vendor:'dataforseo',provider:'perplexity',method:'simulated',unitCostMicros:1}]})},cookie)).status).toBe(400);expect((await call('/api/admin/rates',{method:'PUT',body:JSON.stringify({rates:[{vendor:'serpapi',provider:'google-ai-mode',method:'simulated',unitCostMicros:1.5}]})},cookie)).status).toBe(400);expect((await call('/api/admin/rates',{method:'PUT',body:JSON.stringify({rates:[{vendor:'serpapi',provider:'google-ai-mode',method:'simulated',unitCostMicros:15000}]})},cookie)).status).toBe(200);const rates=await (await call('/api/admin/rates',{},cookie)).json() as {rates:{vendor:string;provider:string;unitCostMicros:number|null;reportsCost:boolean}[]};expect(rates.rates.find(r=>r.vendor==='serpapi'&&r.provider==='google-ai-mode')?.unitCostMicros).toBe(15000);expect(rates.rates.filter(r=>r.reportsCost).map(r=>r.vendor).sort()).toEqual(['dataforseo','perplexity']);const audit=await (await call('/api/admin/audit',{},cookie)).json() as {events:{type:string}[]};expect(audit.events.map(e=>e.type)).toEqual(expect.arrayContaining(['admin.login','admin.account.controls_updated','admin.rates.updated']))});
  it('signs out and revokes the session',async()=>{const cookie=await signIn();expect((await call('/api/admin/auth/logout',{method:'POST',body:'{}'},cookie)).status).toBe(200);expect((await call('/api/admin/auth/session',{},cookie)).status).toBe(401)});
});
