import { AppError } from '../../core/src/errors';
import { percentile } from './metrics';

/** Read-only Vercel REST client for the control panel. Needs a read-scoped VERCEL_API_TOKEN; VERCEL_TEAM_ID when the projects belong to a team. */
export interface VercelConfig { token?:string; teamId?:string; teamSlug?:string; projectIds:string[] }
export const vercelConfigFromEnv=(env:{VERCEL_API_TOKEN?:string;VERCEL_TEAM_ID?:string;VERCEL_TEAM_SLUG?:string;VERCEL_PROJECT_IDS?:string}):VercelConfig=>({token:env.VERCEL_API_TOKEN||undefined,teamId:env.VERCEL_TEAM_ID||undefined,teamSlug:env.VERCEL_TEAM_SLUG||undefined,projectIds:(env.VERCEL_PROJECT_IDS??'').split(',').map(s=>s.trim()).filter(Boolean)});
export interface Deployment { id:string; url:string; state:string; target:string|null; createdAt:number; buildMs:number|null; branch?:string; commit?:string; message?:string }
export interface ProjectHealth { projectId:string; name:string; deployments:Deployment[]; total:number; failed:number; successRate:number|null; buildP50Ms:number|null; buildP95Ms:number|null; lastProduction:Deployment|null; dashboardUrl:string }

type RawDeployment = { uid:string; url:string; state?:string; readyState?:string; target?:string|null; created?:number; createdAt?:number; buildingAt?:number; ready?:number; meta?:Record<string,string> };
async function get<T>(config:VercelConfig,path:string,params:Record<string,string|number>,fetcher:typeof fetch):Promise<T>{const query=new URLSearchParams(Object.entries(params).map(([k,v])=>[k,String(v)]));if(config.teamId)query.set('teamId',config.teamId);const res=await fetcher(`https://api.vercel.com${path}?${query}`,{headers:{authorization:`Bearer ${config.token}`},signal:AbortSignal.timeout(10_000)});if(res.status===401||res.status===403)throw new AppError('CONFIGURATION_ERROR','Vercel rejected the configured API token.',502);if(!res.ok)throw new AppError('PROVIDER_ERROR',`Vercel returned ${res.status}.`,502,res.status>=500||res.status===429);return res.json() as Promise<T>}
export const toDeployment=(d:RawDeployment):Deployment=>({id:d.uid,url:d.url,state:d.readyState??d.state??'UNKNOWN',target:d.target??null,createdAt:d.createdAt??d.created??0,buildMs:d.ready&&d.buildingAt?d.ready-d.buildingAt:null,branch:d.meta?.githubCommitRef,commit:d.meta?.githubCommitSha?.slice(0,7),message:d.meta?.githubCommitMessage?.split('\n')[0]});
/** Build health from finished deployments; canceled and in-progress ones are excluded from the success rate. */
export function summarizeDeployments(projectId:string,name:string,deployments:Deployment[],dashboardUrl:string):ProjectHealth{const finished=deployments.filter(d=>d.state==='READY'||d.state==='ERROR');const failed=finished.filter(d=>d.state==='ERROR').length;const builds=finished.flatMap(d=>d.state==='READY'&&d.buildMs!==null?[d.buildMs]:[]);return{projectId,name,deployments,total:deployments.length,failed,successRate:finished.length?(finished.length-failed)/finished.length:null,buildP50Ms:percentile(builds,50),buildP95Ms:percentile(builds,95),lastProduction:deployments.find(d=>d.target==='production'&&d.state==='READY')??null,dashboardUrl}}
export async function projectHealth(config:VercelConfig,since:number,fetcher:typeof fetch=fetch):Promise<ProjectHealth[]>{if(!config.token||!config.projectIds.length)throw new AppError('CONFIGURATION_ERROR','Vercel is not connected. Set VERCEL_API_TOKEN and VERCEL_PROJECT_IDS.',503);return Promise.all(config.projectIds.map(async projectId=>{const [project,list]=await Promise.all([get<{name:string;accountId?:string}>(config,`/v9/projects/${encodeURIComponent(projectId)}`,{},fetcher),get<{deployments:RawDeployment[]}>(config,'/v6/deployments',{projectId,since,limit:100},fetcher)]);return summarizeDeployments(projectId,project.name,list.deployments.map(toDeployment),config.teamSlug?`https://vercel.com/${config.teamSlug}/${project.name}/observability`:'https://vercel.com/dashboard')}))}
