import { AppError } from './errors';
import { domainMatches,isMentioned } from './domain';
import { normalizeLocation,resolveSources,sourceKey } from './sources';
import type { Project,ProviderRegistry,Run,RunResult } from './types';
export interface UsageStore { reserve(accountId:string,runId:string,units:number,limit:number):Promise<boolean>; release(accountId:string,runId:string):Promise<void> }
export class MemoryUsageStore implements UsageStore { private reservations=new Map<string,number>(); async reserve(accountId:string,runId:string,units:number,limit:number){const key=`${accountId}:${runId}`;if(this.reservations.has(key))return true;const used=[...this.reservations].filter(([k])=>k.startsWith(`${accountId}:`)).reduce((n,[,u])=>n+u,0);if(used+units>limit)return false;this.reservations.set(key,units);return true}async release(accountId:string,runId:string){this.reservations.delete(`${accountId}:${runId}`)} }
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
export async function withRetry<T>(operation:()=>Promise<T>,attempts=3,delay=10):Promise<T>{let last:unknown;for(let i=1;i<=attempts;i++){try{return await operation()}catch(e){last=e;if(!(e instanceof AppError&&e.recoverable)||i===attempts)throw e;await wait(delay*2**(i-1))}}throw last}
/** Runs every query against every selected source (engine + collection method). One usage unit is one query on one source. */
export async function executeRun(project:Project,queries:string[],providers:ProviderRegistry,usage:UsageStore,maxUnits=500,runId=crypto.randomUUID()):Promise<Run>{const requestId=crypto.randomUUID();const sources=resolveSources(project);const location=normalizeLocation(project.location);const units=queries.length*sources.length;if(!await usage.reserve(project.accountId,runId,units,maxUnits))throw new AppError('QUOTA_EXCEEDED','This run exceeds your available usage allowance.',409);const monitored=[project.primaryDomain,...project.alternateDomains];const tasks=queries.flatMap((query,qi)=>sources.map(async({provider:providerId,method})=>{const started=Date.now();try{const provider=providers[sourceKey(providerId,method)];if(!provider)throw new AppError('CONFIGURATION_ERROR','This AI source is not available right now.',503);const output=await withRetry(()=>provider.runQuery({query,location,requestId}));const cited=output.normalized.citations.filter(c=>domainMatches(c.domain,monitored));return{queryId:`q_${qi}`,query,provider:providerId,method,status:'SUCCESS',result:output.normalized,customerCited:cited.length>0,customerMentioned:isMentioned(output.normalized.answerText,monitored),citationPosition:cited[0]?.position,durationMs:Date.now()-started} satisfies RunResult}catch(error){const known=error instanceof AppError?error:new AppError('PROVIDER_ERROR','Provider request failed.',502);return{queryId:`q_${qi}`,query,provider:providerId,method,status:'FAILED',customerCited:false,customerMentioned:false,durationMs:Date.now()-started,error:{code:known.code,message:known.message,attempts:known.recoverable?3:1}} satisfies RunResult}}));const results=await Promise.all(tasks);const successes=results.filter(r=>r.status==='SUCCESS').length;return{id:runId,accountId:project.accountId,projectId:project.id,status:successes===results.length?'COMPLETED':successes?'COMPLETED_WITH_ERRORS':'FAILED',results,createdAt:new Date().toISOString(),completedAt:new Date().toISOString(),requestId}}
