import JSZip from 'jszip';
import * as XLSX from 'xlsx';
import { AppError } from '../../core/src/errors';
import type { Run } from '../../core/src/types';
const names:Record<string,string>={'google-ai-overview':'Google AI Overview','google-ai-mode':'Google AI Mode','bing-copilot':'Bing Copilot','duckduckgo-search-assist':'DuckDuckGo','naver-ai-overview':'Naver'};
const rows=(run:Run)=>run.results.map(r=>({Query:r.query,Provider:names[r.provider],Status:r.status,'AI answer':r.result?.answerPresent?'Yes':'No',Cited:r.customerCited?'Yes':'No',Mentioned:r.customerMentioned?'Yes':'No','Citation position':r.citationPosition??'',References:r.result?.citations.length??0,Domains:r.result?.uniqueDomains.join(', ')??'',Answer:r.result?.answerText??'',Error:r.error?.message??''}));
export function createWorkbook(run:Run):Uint8Array{const book=XLSX.utils.book_new();const all=rows(run);XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet([{Run:run.id,Status:run.status,Completed:run.completedAt??''}]),'Summary');for(const [,name] of Object.entries(names))XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet(all.filter(r=>r.Provider===name)),name.slice(0,31));XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet(run.results.flatMap(r=>r.result?.citations.map(c=>({Query:r.query,Provider:r.provider,...c}))??[])),'All Citations');XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet(all),'Raw Results');return XLSX.write(book,{bookType:'xlsx',type:'array'})}
export async function createCsvZip(run:Run):Promise<Uint8Array>{const zip=new JSZip();const all=rows(run);zip.file('summary.csv',XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet([{Run:run.id,Status:run.status}])));for(const [id,name] of Object.entries(names))zip.file(`${id}.csv`,XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(all.filter(r=>r.Provider===name))));zip.file('citations.csv',XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(run.results.flatMap(r=>r.result?.citations??[]))));return zip.generateAsync({type:'uint8array'})}
export interface ObjectStore { put(key:string,data:Uint8Array,metadata:Record<string,string>):Promise<void>; signedUrl(key:string,expiresSeconds:number):Promise<string> }
export function authorizeDownload(exportAccountId:string,requestAccountId:string){if(exportAccountId!==requestAccountId)throw new AppError('AUTHORIZATION_ERROR','You cannot access this report.',403)}
