import { Hono } from 'hono';
import type { Context } from 'hono';
import { AppError,ValidationError,errorResponse } from '../../../packages/core/src/errors';
import { methodLabels,providerMethods,sourceKey } from '../../../packages/core/src/sources';
import { answerEngineProviderIds,providerIds,providerNames } from '../../../packages/core/src/types';
import type { AnswerEngineProviderId,CollectionMethod,ProviderId } from '../../../packages/core/src/types';
import { providerConfigFromEnv,simulatedVendorSupport,sourceAvailability } from '../../../packages/providers/src/index';
import type { ProviderConfig } from '../../../packages/providers/src/index';
import { LOGIN_TOKEN_TTL_MS,MAX_LOGIN_ATTEMPTS,SESSION_COOKIE,SESSION_TTL_MS,base32Decode,decryptSecret,randomToken,readCookie,sessionCookie,sha256Hex,verifyTotp } from '../../../packages/admin/src/auth';
import { accountMargins,businessMetrics,costBreakdown,parseRange,percentile,periodRevenueCents } from '../../../packages/admin/src/metrics';
import type { CallGroup,CostDimension,Period,SubscriptionRow } from '../../../packages/admin/src/metrics';
import { applyRouting,emptyRouting,maskAvailability,parseRouting,readRouting,sourceVendor,vendorNames } from '../../../packages/admin/src/routing';
import type { RoutingOverrides,Vendor } from '../../../packages/admin/src/routing';
import { projectHealth,vercelConfigFromEnv } from '../../../packages/admin/src/vercel';

/** Operator control panel API, served at /api/admin and reached from admin.aioverviewhub.com through a same-origin Vercel rewrite.
 * Every route except sign-in requires an operator session; every change is written to audit_events. Vendor names are visible here, unlike the customer API. */
type Row=Record<string,unknown>;
type Statement={first<T=Row>():Promise<T|null>;all<T=Row>():Promise<{results:T[]}>;run():Promise<{meta?:{changes?:number}}>};
export type AdminDB={prepare(sql:string):Statement&{bind(...values:unknown[]):Statement}};
export type AdminEnv={DB:AdminDB;QUEUE:{send(value:unknown):Promise<void>};ADMIN_URL?:string;ADMIN_ORIGIN?:string;ADMIN_TOTP_KEY?:string;EMAIL_PROVIDER?:string;VERCEL_API_TOKEN?:string;VERCEL_TEAM_ID?:string;VERCEL_TEAM_SLUG?:string;VERCEL_PROJECT_IDS?:string}&Record<string,unknown>;
interface Operator { id:string; email:string; name:string|null }
type AdminContext=Context<{Bindings:AdminEnv;Variables:{operator:Operator;requestId:string}}>;

const all=async<T=Row>(db:AdminDB,sql:string,...values:unknown[])=>(await db.prepare(sql).bind(...values).all<T>()).results;
const one=<T=Row>(db:AdminDB,sql:string,...values:unknown[])=>db.prepare(sql).bind(...values).first<T>();
const exec=(db:AdminDB,sql:string,...values:unknown[])=>db.prepare(sql).bind(...values).run();
const now=()=>new Date().toISOString();
const body=async<T>(c:AdminContext)=>{try{return await c.req.json<T>()}catch{throw new ValidationError('Request body must be JSON.')}};
const audit=(c:AdminContext,type:string,metadata:Record<string,unknown>,accountId:string|null=null)=>exec(c.env.DB,'INSERT INTO audit_events (id,account_id,user_id,type,request_id,metadata,created_at) VALUES (?,?,?,?,?,?,?)',crypto.randomUUID(),accountId,c.get('operator')?.id??null,type,c.get('requestId'),JSON.stringify({operator:c.get('operator')?.email,...metadata}),now());

/** Global routing overrides from operator_settings. Read leniently so a bad row never takes customer sources offline. */
export async function loadGlobalRouting(db:{prepare(sql:string):{bind(...v:unknown[]):{first<T>():Promise<T|null>}}}):Promise<RoutingOverrides>{try{const row=await db.prepare('SELECT value FROM operator_settings WHERE key=?').bind('routing').first<{value?:string}>();return readRouting(row?.value)}catch{return emptyRouting()}}
/** Per-account controls for the run consumer: whether the account may run, and the routing layer to apply on top of the global one. */
export async function loadAccountControls(db:AdminDB,accountId:string){const row=await one<{status:string;simulated_vendors:string;disabled_sources:string;max_queries_override:number|null;addon_waived:number}>(db,'SELECT status,simulated_vendors,disabled_sources,max_queries_override,addon_waived FROM account_controls WHERE account_id=?',accountId);return{paused:row?.status==='paused',routing:row?readRouting(JSON.stringify({simulatedVendors:JSON.parse(row.simulated_vendors||'{}'),disabledSources:JSON.parse(row.disabled_sources||'[]')})):emptyRouting(),maxQueriesOverride:row?.max_queries_override??null,addonWaived:Boolean(row?.addon_waived)}}

const admin=new Hono<{Bindings:AdminEnv;Variables:{operator:Operator;requestId:string}}>();
admin.use('*',async(c,next)=>{c.set('requestId',c.req.header('x-request-id')??crypto.randomUUID());c.header('cache-control','no-store');c.header('x-robots-tag','noindex');
  // Mutations must come from the admin origin as JSON. With the SameSite=Strict session cookie this blocks cross-site request forgery.
  if(c.req.method!=='GET'&&c.req.method!=='HEAD'){const origin=c.req.header('origin');if(origin&&c.env.ADMIN_ORIGIN&&origin!==c.env.ADMIN_ORIGIN)throw new AppError('AUTHORIZATION_ERROR','Cross-origin requests are not allowed.',403);if(!c.req.header('content-type')?.startsWith('application/json'))throw new ValidationError('Requests must be JSON.')}
  await next()});

// --- Sign-in: emailed one-time link, then an authenticator-app code. ---
admin.post('/auth/start',async c=>{const {email}=await body<{email?:string}>(c);const address=String(email??'').trim().toLowerCase();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(address)||address.length>254)throw new ValidationError('Enter a valid email address.');if(!c.env.ADMIN_URL||c.env.EMAIL_PROVIDER!=='console')throw new AppError('CONFIGURATION_ERROR','Admin sign-in email is not configured.',503);
  const operator=await one<{id:string}>(c.env.DB,'SELECT id FROM operators WHERE email=? AND active=1',address);
  // The response is identical whether or not the address is an operator, so the endpoint cannot be used to discover operator emails.
  if(operator){const recent=await one<{n:number}>(c.env.DB,'SELECT COUNT(*) n FROM operator_login_tokens WHERE operator_id=? AND created_at>?',operator.id,new Date(Date.now()-LOGIN_TOKEN_TTL_MS).toISOString());if((recent?.n??0)<3){const token=randomToken();await exec(c.env.DB,'INSERT INTO operator_login_tokens (token_hash,operator_id,expires_at,created_at) VALUES (?,?,?,?)',await sha256Hex(token),operator.id,new Date(Date.now()+LOGIN_TOKEN_TTL_MS).toISOString(),now());
    // The token travels in the URL fragment, which browsers never send to servers or in Referer headers.
    console.log(JSON.stringify({level:'info',event:'admin_login_link',to:address,link:`${c.env.ADMIN_URL}/login#token=${token}`}))}}
  return c.json({success:true},202)});
admin.post('/auth/verify',async c=>{const {token,code}=await body<{token?:string;code?:string}>(c);if(!token||!code)throw new ValidationError('Sign-in link and code are required.');const hash=await sha256Hex(token);const denied=new AppError('AUTHENTICATION_ERROR','That code or sign-in link is not valid. Request a new link if it has expired.',401);
  const login=await one<{operator_id:string;expires_at:string;used_at:string|null;attempts:number;totp_secret:string;last_totp_step:number;email:string;name:string|null;active:number}>(c.env.DB,'SELECT t.operator_id,t.expires_at,t.used_at,t.attempts,o.totp_secret,o.last_totp_step,o.email,o.name,o.active FROM operator_login_tokens t JOIN operators o ON o.id=t.operator_id WHERE t.token_hash=?',hash);
  if(!login||login.used_at||login.expires_at<now()||!login.active)throw denied;
  // Count the attempt before checking the code so parallel guesses cannot exceed the limit.
  const counted=await exec(c.env.DB,'UPDATE operator_login_tokens SET attempts=attempts+1 WHERE token_hash=? AND attempts<?',hash,MAX_LOGIN_ATTEMPTS);if(!counted.meta?.changes)throw denied;
  const step=await verifyTotp(base32Decode(await decryptSecret(login.totp_secret,c.env.ADMIN_TOTP_KEY)),String(code).replace(/\s/g,''),login.last_totp_step);if(step===null)throw denied;
  const claimed=await exec(c.env.DB,'UPDATE operator_login_tokens SET used_at=? WHERE token_hash=? AND used_at IS NULL',now(),hash);const stepped=await exec(c.env.DB,'UPDATE operators SET last_totp_step=? WHERE id=? AND last_totp_step<?',step,login.operator_id,step);if(!claimed.meta?.changes||!stepped.meta?.changes)throw denied;
  const session=randomToken();await exec(c.env.DB,'INSERT INTO operator_sessions (token_hash,operator_id,expires_at,created_at) VALUES (?,?,?,?)',await sha256Hex(session),login.operator_id,new Date(Date.now()+SESSION_TTL_MS).toISOString(),now());
  c.set('operator',{id:login.operator_id,email:login.email,name:login.name});await audit(c,'admin.login',{});c.header('set-cookie',sessionCookie(session));return c.json({success:true,operator:{email:login.email,name:login.name}})});

// Everything below requires an operator session.
admin.use('*',async(c,next)=>{if(c.req.path.endsWith('/auth/start')||c.req.path.endsWith('/auth/verify'))return next();const token=readCookie(c.req.header('cookie'),SESSION_COOKIE);const operator=token?await one<Operator>(c.env.DB,'SELECT o.id,o.email,o.name FROM operator_sessions s JOIN operators o ON o.id=s.operator_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>? AND o.active=1',await sha256Hex(token),now()):null;if(!operator)throw new AppError('AUTHENTICATION_ERROR','Sign in to continue.',401);c.set('operator',operator);await next()});
admin.get('/auth/session',c=>c.json({success:true,operator:{email:c.get('operator').email,name:c.get('operator').name}}));
admin.post('/auth/logout',async c=>{const token=readCookie(c.req.header('cookie'),SESSION_COOKIE)!;await exec(c.env.DB,'UPDATE operator_sessions SET revoked_at=? WHERE token_hash=?',now(),await sha256Hex(token));await audit(c,'admin.logout',{});c.header('set-cookie',sessionCookie('',0));return c.json({success:true})});

// --- Metrics ---
const costGroups=(db:AdminDB,p:Period,accountId?:string)=>all<CallGroup>(db,`SELECT r.account_id accountId,COALESCE(a.name,r.account_id) accountName,q.provider_id provider,q.method,q.vendor,q.status,COUNT(*) calls,COALESCE(SUM(q.cost_micros),0) costMicros,SUM(CASE WHEN q.status='SUCCESS' AND q.cost_micros IS NULL THEN 1 ELSE 0 END) unpricedCalls FROM run_queries q JOIN runs r ON r.id=q.run_id LEFT JOIN accounts a ON a.id=r.account_id WHERE q.completed_at>=? AND q.completed_at<?${accountId?' AND r.account_id=?':''} GROUP BY r.account_id,accountName,q.provider_id,q.method,q.vendor,q.status`,...[p.from,p.to,...(accountId?[accountId]:[])]);
const subscriptions=(db:AdminDB)=>all<SubscriptionRow&{accountName:string}>(db,'SELECT s.account_id accountId,COALESCE(a.name,s.account_id) accountName,s.plan_id planId,s.status,p.monthly_price monthlyPrice,s.created_at createdAt,s.canceled_at canceledAt FROM subscriptions s JOIN plans p ON p.id=s.plan_id LEFT JOIN accounts a ON a.id=s.account_id');
/** Add-on revenue: billable add-on checks at the subscription plan's add-on price, excluding accounts whose add-ons are waived and plans without a price yet. */
const addonRevenue=(db:AdminDB,p:Period)=>all<{accountId:string;checks:number;cents:number}>(db,"SELECT u.account_id accountId,COUNT(*) checks,COALESCE(SUM(p.addon_unit_price),0) cents FROM usage_events u JOIN subscriptions s ON s.id=u.subscription_id JOIN plans p ON p.id=s.plan_id LEFT JOIN account_controls ac ON ac.account_id=u.account_id WHERE u.addon=1 AND u.created_at>=? AND u.created_at<? AND COALESCE(ac.addon_waived,0)=0 GROUP BY u.account_id",p.from,p.to);
async function business(db:AdminDB,p:Period){const [subs,addons]=await Promise.all([subscriptions(db),addonRevenue(db,p)]);const addonCents=addons.reduce((n,a)=>n+a.cents,0);const metrics=businessMetrics(subs,p,addonCents);const paying=subs.filter(s=>['active','trialing','past_due'].includes(s.status));const revenue=new Map<string,{accountId:string;accountName:string;revenueCents:number}>();for(const s of paying){const r=revenue.get(s.accountId)??{accountId:s.accountId,accountName:s.accountName,revenueCents:0};r.revenueCents+=periodRevenueCents(s.monthlyPrice,p);revenue.set(s.accountId,r)}for(const a of addons){const r=revenue.get(a.accountId);if(r)r.revenueCents+=a.cents}
  // Twelve-month new vs churned subscriptions for the trend chart.
  const months=Array.from({length:12},(_,i)=>{const d=new Date();d.setUTCDate(1);d.setUTCHours(0,0,0,0);d.setUTCMonth(d.getUTCMonth()-11+i);return d.toISOString().slice(0,7)});const trend=months.map(month=>({month,new:subs.filter(s=>s.createdAt?.startsWith(month)).length,churned:subs.filter(s=>s.canceledAt?.startsWith(month)).length}));
  return{metrics,revenueCents:[...revenue.values()].reduce((n,r)=>n+r.revenueCents,0),revenueByAccount:[...revenue.values()],trend}}
async function operations(db:AdminDB,p:Period){const [groups,errors,durations,jobs,failedJobs,runs,webhooks]=await Promise.all([costGroups(db,p),all<{provider:ProviderId;method:CollectionMethod;code:string|null;n:number}>(db,"SELECT provider_id provider,method,error_code code,COUNT(*) n FROM run_queries WHERE status='FAILED' AND completed_at>=? AND completed_at<? GROUP BY provider_id,method,error_code",p.from,p.to),all<{provider:ProviderId;method:CollectionMethod;ms:number}>(db,'SELECT provider_id provider,method,duration_ms ms FROM run_queries WHERE duration_ms IS NOT NULL AND completed_at>=? AND completed_at<? ORDER BY completed_at DESC LIMIT 20000',p.from,p.to),all<{status:string;n:number}>(db,'SELECT status,COUNT(*) n FROM scheduled_jobs GROUP BY status'),all(db,"SELECT id,account_id accountId,project_id projectId,job_type jobType,attempts,error_code errorCode,request_id requestId,updated_at updatedAt FROM scheduled_jobs WHERE status='FAILED' ORDER BY updated_at DESC LIMIT 25"),all<{status:string;n:number}>(db,'SELECT status,COUNT(*) n FROM runs WHERE created_at>=? AND created_at<? GROUP BY status',p.from,p.to),all<{status:string;n:number}>(db,'SELECT status,COUNT(*) n FROM webhook_events WHERE received_at>=? AND received_at<? GROUP BY status',p.from,p.to)]);
  const sources=costBreakdown(groups,'source').map(line=>{const [provider,method]=line.key.split(':') as [ProviderId,CollectionMethod];const ms=durations.filter(d=>d.provider===provider&&d.method===method).map(d=>d.ms);return{...line,errorRate:line.calls?line.failures/line.calls:null,p50Ms:percentile(ms,50),p95Ms:percentile(ms,95),errors:errors.filter(e=>e.provider===provider&&e.method===method).map(e=>({code:e.code??'UNKNOWN',count:e.n})).sort((a,b)=>b.count-a.count)}});
  const counts=(rows:{status:string;n:number}[])=>Object.fromEntries(rows.map(r=>[r.status,r.n]));return{sources,jobs:counts(jobs),failedJobs,runs:counts(runs),webhooks:counts(webhooks)}}

admin.get('/overview',async c=>{const p=parseRange(c.req.query('range'));const [biz,groups,ops]=await Promise.all([business(c.env.DB,p),costGroups(c.env.DB,p),operations(c.env.DB,p)]);const costMicros=groups.reduce((n,g)=>n+g.costMicros,0);const checks=groups.reduce((n,g)=>n+g.calls,0);const revenueMicros=biz.revenueCents*10_000;return c.json({success:true,period:p,business:biz.metrics,revenueCents:biz.revenueCents,costMicros,checks,grossMarginRate:revenueMicros?(revenueMicros-costMicros)/revenueMicros:null,topSources:costBreakdown(groups,'source').slice(0,5),health:{runs:ops.runs,jobs:ops.jobs,failedJobs:ops.failedJobs.length,webhooks:ops.webhooks,degradedSources:ops.sources.filter(s=>(s.errorRate??0)>0.1).map(s=>({key:s.key,label:s.label,errorRate:s.errorRate}))}})});
admin.get('/costs',async c=>{const p=parseRange(c.req.query('range'));const accountId=c.req.query('accountId')||undefined;const by=(['source','vendor','account'] as const).find(d=>d===c.req.query('by'))??'source' satisfies CostDimension;const [groups,daily,biz]=await Promise.all([costGroups(c.env.DB,p,accountId),all<{day:string;costMicros:number;calls:number}>(c.env.DB,`SELECT substr(q.completed_at,1,10) day,COALESCE(SUM(q.cost_micros),0) costMicros,COUNT(*) calls FROM run_queries q JOIN runs r ON r.id=q.run_id WHERE q.completed_at>=? AND q.completed_at<?${accountId?' AND r.account_id=?':''} GROUP BY day ORDER BY day`,...[p.from,p.to,...(accountId?[accountId]:[])]),business(c.env.DB,p)]);const lines=costBreakdown(groups,by);return c.json({success:true,period:p,by,lines,daily,totalMicros:lines.reduce((n,l)=>n+l.costMicros,0),unpricedCalls:lines.reduce((n,l)=>n+l.unpricedCalls,0),margins:by==='account'?accountMargins(biz.revenueByAccount.filter(r=>!accountId||r.accountId===accountId),lines):undefined})});
admin.get('/business',async c=>{const p=parseRange(c.req.query('range'));const [biz,groups]=await Promise.all([business(c.env.DB,p),costGroups(c.env.DB,p)]);const costs=costBreakdown(groups,'account');return c.json({success:true,period:p,...biz.metrics,revenueCents:biz.revenueCents,costMicros:costs.reduce((n,l)=>n+l.costMicros,0),trend:biz.trend,margins:accountMargins(biz.revenueByAccount,costs)})});
admin.get('/operations',async c=>{const p=parseRange(c.req.query('range'));return c.json({success:true,period:p,...await operations(c.env.DB,p)})});
admin.get('/vercel',async c=>{const p=parseRange(c.req.query('range'));return c.json({success:true,period:p,projects:await projectHealth(vercelConfigFromEnv(c.env),Date.parse(p.from))})});

// --- Data sources: which vendor serves each source, and kill switches. ---
const envConfig=(env:AdminEnv):{config?:ProviderConfig;error?:string}=>{try{return{config:providerConfigFromEnv(env)}}catch(error){return{error:error instanceof Error?error.message:'Invalid provider configuration.'}}};
admin.get('/sources',async c=>{const routing=await loadGlobalRouting(c.env.DB);const env=envConfig(c.env);if(!env.config)return c.json({success:true,routing,configError:env.error,sources:[]});const {config,disabled}=applyRouting(env.config,routing);const available=sourceAvailability(config);
  return c.json({success:true,routing,mock:Boolean(config.mock),sources:providerIds.flatMap(id=>providerMethods[id].map(method=>{const key=sourceKey(id,method);const vendor=sourceVendor(id,method,config);const engine=id as AnswerEngineProviderId;const switchable=method==='simulated'&&answerEngineProviderIds.includes(engine);return{key,provider:id,method,label:`${providerNames[id]} · ${methodLabels[method].label}`,vendor,vendorName:vendorNames[vendor],envVendor:sourceVendor(id,method,env.config!),vendorOptions:switchable?simulatedVendorSupport[engine].map(v=>({vendor:v,name:vendorNames[v],configured:sourceAvailability({...config,simulatedVendors:{...config.simulatedVendors,[engine]:v}})[key]})):[],credentialsConfigured:available[key],disabled:disabled.has(key),live:maskAvailability(available,disabled)[key]}}))})});
admin.put('/sources/routing',async c=>{const next=parseRouting(await body(c));const env=envConfig(c.env);if(env.config){const {config}=applyRouting(env.config,next);const available=sourceAvailability(config);const missing=Object.entries(next.simulatedVendors).filter(([engine])=>!available[sourceKey(engine as ProviderId,'simulated')]);if(missing.length)throw new ValidationError(`${missing.map(([e,v])=>`${vendorNames[v as Vendor]} has no credentials for ${providerNames[e as ProviderId]}`).join('; ')}. Add the credentials before switching.`)}const before=await loadGlobalRouting(c.env.DB);await exec(c.env.DB,'INSERT INTO operator_settings (key,value,updated_by,updated_at) VALUES (?,?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_by=excluded.updated_by,updated_at=excluded.updated_at','routing',JSON.stringify(next),c.get('operator').id,now());await audit(c,'admin.routing.updated',{before,after:next});return c.json({success:true,routing:next})});

// --- Vendor cost rates ---
/** Every vendor/source pair that can incur cost, and whether the vendor reports per-call cost itself (then a rate is only a fallback). */
export const rateSlots=providerIds.flatMap(provider=>providerMethods[provider].flatMap(method=>{const engine=provider as AnswerEngineProviderId;const vendors:Vendor[]=method==='api'?[provider==='chatgpt'?'openai':'perplexity']:answerEngineProviderIds.includes(engine)?[...simulatedVendorSupport[engine]]:['serpapi'];return vendors.map(vendor=>({vendor,vendorName:vendorNames[vendor],provider,method,label:`${providerNames[provider]} · ${methodLabels[method].label}`,reportsCost:vendor==='perplexity'||vendor==='dataforseo'}))}));
admin.get('/rates',async c=>{const rows=await all<{vendor:string;provider_id:string;method:string;unit_cost_micros:number;updated_at:string}>(c.env.DB,'SELECT vendor,provider_id,method,unit_cost_micros,updated_at FROM vendor_rates');return c.json({success:true,rates:rateSlots.map(s=>{const r=rows.find(r=>r.vendor===s.vendor&&r.provider_id===s.provider&&r.method===s.method);return{...s,unitCostMicros:r?.unit_cost_micros??null,updatedAt:r?.updated_at??null}})})});
admin.put('/rates',async c=>{const {rates}=await body<{rates?:{vendor:string;provider:string;method:string;unitCostMicros:number|null}[]}>(c);if(!Array.isArray(rates)||!rates.length||rates.length>100)throw new ValidationError('Provide between 1 and 100 rates.');for(const r of rates){if(!rateSlots.some(s=>s.vendor===r.vendor&&s.provider===r.provider&&s.method===r.method))throw new ValidationError(`${r.vendor} does not serve ${r.provider}:${r.method}.`);if(r.unitCostMicros!==null&&!(Number.isInteger(r.unitCostMicros)&&r.unitCostMicros>=0&&r.unitCostMicros<=100_000_000))throw new ValidationError('Rates must be whole micro-dollars between 0 and 100,000,000 ($100).')}
  for(const r of rates){if(r.unitCostMicros===null)await exec(c.env.DB,'DELETE FROM vendor_rates WHERE vendor=? AND provider_id=? AND method=?',r.vendor,r.provider,r.method);else await exec(c.env.DB,'INSERT INTO vendor_rates (vendor,provider_id,method,unit_cost_micros,updated_by,updated_at) VALUES (?,?,?,?,?,?) ON CONFLICT(vendor,provider_id,method) DO UPDATE SET unit_cost_micros=excluded.unit_cost_micros,updated_by=excluded.updated_by,updated_at=excluded.updated_at',r.vendor,r.provider,r.method,r.unitCostMicros,c.get('operator').id,now())}await audit(c,'admin.rates.updated',{rates});return c.json({success:true})});

// --- Customer accounts ---
admin.get('/accounts',async c=>{const p=parseRange(c.req.query('range'));const search=`%${(c.req.query('q')??'').trim().toLowerCase()}%`;const [rows,groups,biz]=await Promise.all([all(c.env.DB,`SELECT a.id,a.name,a.created_at createdAt,s.status subscriptionStatus,s.plan_id planId,p.monthly_price monthlyPrice,COALESCE(ac.status,'active') status,ac.addon_waived addonWaived,ac.max_queries_override maxQueriesOverride,(SELECT MAX(created_at) FROM runs WHERE account_id=a.id) lastRunAt FROM accounts a LEFT JOIN subscriptions s ON s.id=(SELECT id FROM subscriptions WHERE account_id=a.id ORDER BY updated_at DESC LIMIT 1) LEFT JOIN plans p ON p.id=s.plan_id LEFT JOIN account_controls ac ON ac.account_id=a.id WHERE lower(a.name) LIKE ? OR a.id LIKE ? ORDER BY a.created_at DESC LIMIT 500`,search,search),costGroups(c.env.DB,p),business(c.env.DB,p)]);const margins=new Map(accountMargins(biz.revenueByAccount,costBreakdown(groups,'account')).map(m=>[m.accountId,m]));const checks=new Map(costBreakdown(groups,'account').map(l=>[l.key,l]));return c.json({success:true,period:p,accounts:rows.map(r=>{const id=String(r.id);const m=margins.get(id);const l=checks.get(id);return{...r,addonWaived:Boolean(r.addonWaived),checks:l?.calls??0,failures:l?.failures??0,costMicros:m?.costMicros??0,revenueCents:m?.revenueCents??0,marginRate:m?.marginRate??null}})})});
admin.get('/accounts/:id',async c=>{const id=c.req.param('id');const p=parseRange(c.req.query('range'));const account=await one(c.env.DB,'SELECT id,name,created_at createdAt FROM accounts WHERE id=?',id);if(!account)throw new AppError('VALIDATION_ERROR','Account not found.',404);const [controls,subs,projects,runs,groups,members]=await Promise.all([loadAccountControls(c.env.DB,id),all(c.env.DB,'SELECT s.id,s.plan_id planId,p.name planName,s.status,p.monthly_price monthlyPrice,s.period_start periodStart,s.period_end periodEnd,s.created_at createdAt,s.canceled_at canceledAt FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE s.account_id=? ORDER BY s.updated_at DESC',id),all(c.env.DB,'SELECT id,name,primary_domain primaryDomain,providers,source_methods sourceMethods,location,frequency,last_run_at lastRunAt FROM projects WHERE account_id=? ORDER BY created_at DESC',id),all(c.env.DB,"SELECT r.id,r.project_id projectId,r.status,r.created_at createdAt,r.completed_at completedAt,COUNT(q.id) checks,SUM(CASE WHEN q.status='FAILED' THEN 1 ELSE 0 END) failures,COALESCE(SUM(q.cost_micros),0) costMicros FROM runs r LEFT JOIN run_queries q ON q.run_id=r.id WHERE r.account_id=? GROUP BY r.id ORDER BY r.created_at DESC LIMIT 25",id),costGroups(c.env.DB,p,id),all(c.env.DB,'SELECT u.email,au.role FROM account_users au JOIN users u ON u.id=au.user_id WHERE au.account_id=?',id)]);return c.json({success:true,period:p,account,controls,subscriptions:subs,projects,runs,members,costs:costBreakdown(groups,'source')})});
admin.put('/accounts/:id/controls',async c=>{const id=c.req.param('id');if(!await one(c.env.DB,'SELECT id FROM accounts WHERE id=?',id))throw new AppError('VALIDATION_ERROR','Account not found.',404);const input=await body<{status?:string;simulatedVendors?:unknown;disabledSources?:unknown;maxQueriesOverride?:number|null;addonWaived?:boolean;notes?:string}>(c);const status=input.status??'active';if(status!=='active'&&status!=='paused')throw new ValidationError('Status must be active or paused.');const routing=parseRouting({simulatedVendors:input.simulatedVendors,disabledSources:input.disabledSources});const max=input.maxQueriesOverride??null;if(max!==null&&!(Number.isInteger(max)&&max>=0&&max<=100_000))throw new ValidationError('Query limit must be a whole number up to 100,000.');const notes=input.notes?String(input.notes).slice(0,2000):null;const before=await loadAccountControls(c.env.DB,id);
  await exec(c.env.DB,'INSERT INTO account_controls (account_id,status,simulated_vendors,disabled_sources,max_queries_override,addon_waived,notes,updated_by,updated_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(account_id) DO UPDATE SET status=excluded.status,simulated_vendors=excluded.simulated_vendors,disabled_sources=excluded.disabled_sources,max_queries_override=excluded.max_queries_override,addon_waived=excluded.addon_waived,notes=excluded.notes,updated_by=excluded.updated_by,updated_at=excluded.updated_at',id,status,JSON.stringify(routing.simulatedVendors),JSON.stringify(routing.disabledSources),max,input.addonWaived?1:0,notes,c.get('operator').id,now());
  const after={paused:status==='paused',routing,maxQueriesOverride:max,addonWaived:Boolean(input.addonWaived)};await audit(c,'admin.account.controls_updated',{before,after,...(notes?{notes}:{})},id);return c.json({success:true,controls:after})});

// --- Failed jobs and audit log ---
admin.post('/jobs/:id/retry',async c=>{const job=await one<{id:string;account_id:string;project_id:string;job_type:string}>(c.env.DB,"SELECT id,account_id,project_id,job_type FROM scheduled_jobs WHERE id=? AND status='FAILED'",c.req.param('id'));if(!job)throw new AppError('VALIDATION_ERROR','Only failed jobs can be retried.',409);await exec(c.env.DB,"UPDATE scheduled_jobs SET status='PENDING',next_attempt_at=?,updated_at=? WHERE id=? AND status='FAILED'",now(),now(),job.id);await c.env.QUEUE.send({type:'JOB_RETRY',jobId:job.id,jobType:job.job_type,accountId:job.account_id,projectId:job.project_id,requestId:c.get('requestId')});await audit(c,'admin.job.retried',{jobId:job.id},job.account_id);return c.json({success:true,status:'PENDING'},202)});
admin.get('/audit',async c=>{const limit=Math.min(Math.max(Number(c.req.query('limit'))||100,1),500);const rows=await all<{id:string;accountId:string|null;type:string;requestId:string;metadata:string|null;createdAt:string}>(c.env.DB,"SELECT id,account_id accountId,type,request_id requestId,metadata,created_at createdAt FROM audit_events WHERE type LIKE 'admin.%' ORDER BY created_at DESC LIMIT ?",limit);return c.json({success:true,events:rows.map(r=>({...r,metadata:r.metadata?JSON.parse(r.metadata):null}))})});

admin.onError((error,c)=>{const status=error instanceof AppError?error.status:500;return c.json(errorResponse(error,c.get('requestId')??crypto.randomUUID()),status as 400)});
export default admin;
