import { AppError, ProviderTimeoutError } from '../../core/src/errors';
import { normalizeDomain } from '../../core/src/domain';
import type { Citation,CollectionMethod,NormalizedAIResult,ProviderId } from '../../core/src/types';

export const get=(source:unknown,path:string[]):unknown=>path.reduce<unknown>((v,k)=>v&&typeof v==='object'?(v as Record<string,unknown>)[k]:undefined,source);
export const first=(raw:unknown,paths:string[][])=>paths.map(p=>get(raw,p)).find(v=>v!==undefined);
export const textFrom=(v:unknown):string=>typeof v==='string'?v:Array.isArray(v)?v.map(textFrom).filter(Boolean).join('\n'):v&&typeof v==='object'?textFrom((v as Record<string,unknown>).text??(v as Record<string,unknown>).snippet??''):'';
/** Converts URL strings or {link|url|source,title,snippet} records into positioned citations, keeping the first occurrence of each URL. */
export const citationsFrom=(v:unknown):Citation[]=>{if(!Array.isArray(v))return[];const seen=new Set<string>();return v.flatMap(item=>{if(typeof item==='string')item={link:item};if(!item||typeof item!=='object')return[];const r=item as Record<string,unknown>;const url=String(r.link??r.url??r.source??'');if(!url||seen.has(url))return[];try{const domain=normalizeDomain(url);seen.add(url);return[{url,title:String(r.title??'')||undefined,abstract:String(r.snippet??r.abstract??r.description??'')||undefined,domain}]}catch{return[]}}).map((c,index)=>({...c,position:index+1}))};
/** Performs a provider HTTP call and maps transport failures onto retryable or permanent AppErrors. */
export async function fetchProviderJson(name:string,fetcher:typeof fetch,url:string,init:RequestInit,timeoutMs=25_000):Promise<unknown>{let response:Response;try{response=await fetcher(url,{...init,signal:AbortSignal.timeout(timeoutMs)})}catch(error){if(error instanceof DOMException||error instanceof Error)throw new ProviderTimeoutError(name);throw error}if(response.status===429)throw new AppError('PROVIDER_RATE_LIMIT',`${name} is temporarily rate limited.`,429,true);if(response.status===401||response.status===403)throw new AppError('CONFIGURATION_ERROR',`${name} rejected the configured credentials.`,502);if(!response.ok)throw new AppError('PROVIDER_ERROR',`${name} returned an unavailable response.`,502,response.status>=500);try{return await response.json()}catch{throw new AppError('PROVIDER_ERROR',`${name} returned an unreadable response.`,502)}}
export const requireCredential=(name:string,...values:(string|undefined)[])=>{if(values.some(v=>!v))throw new AppError('CONFIGURATION_ERROR',`${name} is not configured.`,503)};
export const basicAuth=(user:string,password:string)=>`Basic ${btoa(`${user}:${password}`)}`;
export const buildResult=(provider:ProviderId,method:CollectionMethod,answer:string,citations:Citation[],searchId:unknown,metadata:Record<string,unknown>):NormalizedAIResult=>({provider,method,answerPresent:Boolean(answer.trim()),answerText:answer,citations,uniqueDomains:[...new Set(citations.map(c=>c.domain))],searchId:typeof searchId==='string'&&searchId?searchId:undefined,executedAt:new Date().toISOString(),metadata});
